update webpack-cli
Changes to fix error building in dockerhub:
```
[91m/tfdnapredictions/portal/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,

TypeError: Cannot read property 'properties' of undefined
```

Found solution here: https://github.com/plotly/dash-component-boilerplate/issues/12